import { defineCollection, defineContentConfig, z } from '@nuxt/content'
import { BOOK_CODES, CHAPTERS } from './shared/taxonomy'

// ─────────────────────────────────────────────────────────────────────────────
// This schema is a deliberate SUPERSET of the `teachingResources` collection in
// the ck-teaching repo (coursekata/ck-teaching → content.config.ts). Every field
// below that also exists there is byte-identical, so these markdown files can be
// copied into that repo unchanged.
//
// Only two fields are additions, both optional, so existing ck-teaching
// resources still validate if this schema is ever merged upstream:
//
//   video     — the Vimeo recording that accompanies the notebook
//   sequence  — 1..16 running order (this is a course, not a browse catalog)
//   coverage  — ABC / XCD section ranges the lecture spans
//   schedule  — week + day in the 5-week intensive calendar
//   preview   — generated nbconvert render (scripts/build-previews.mjs)
// ─────────────────────────────────────────────────────────────────────────────

export default defineContentConfig({
  collections: {
    teachingResources: defineCollection({
      type: 'page',
      source: 'resources/**/*.md',
      schema: z.object({
        seo: z.object({}).editor({ hidden: true }),
        navigation: z.boolean().editor({ hidden: true }),
        type: z.enum(['notebook', 'quiz', 'cheatsheet', 'pacing', 'dataset']),
        subtype: z.enum(['mini', 'investigation', 'project', 'assessment', 'overview']).optional(),
        function: z.enum(['teaching', 'assessment', 'planning']).default('teaching'),
        description: z.string(),
        dataset: z.string().optional(),
        books: z
          .object(Object.fromEntries(BOOK_CODES.map((code) => [code, z.boolean().default(false)])))
          .default({}),
        chapter: z.enum(CHAPTERS).optional(),
        tags: z.array(z.string()).default([]),
        files: z
          .array(
            z.object({
              src: z.string().editor({ input: 'media' }),
              label: z.string(),
              role: z.enum(['student', 'teacher', 'supplement']).optional(),
            }),
          )
          .min(1),
        featured: z.boolean().default(false),
        published: z.boolean().default(true),

        // ── additions (see note above) ──────────────────────────────────────
        /** Accompanying recording. Omit while a video is still being uploaded. */
        video: z
          .object({
            provider: z.enum(['vimeo', 'youtube']).default('vimeo'),
            /** Vimeo numeric id, e.g. '824804225'. */
            id: z.string(),
            /** Unlisted-video hash, if the Vimeo privacy setting requires one. */
            hash: z.string().optional(),
            /** Display only, e.g. '12:04'. */
            duration: z.string().optional(),
          })
          .optional(),
        /** Running order within the asynchronous course, 1-16. */
        sequence: z.number().optional(),
        /**
         * Full section coverage. `chapter` above stays a single value so these
         * files keep working with ck-teaching's existing chapter filter; this
         * records the real range for both book configurations.
         */
        coverage: z
          .object({
            abc: z.string().optional(),
            xcd: z.string().optional(),
          })
          .optional(),
        /** Placement in the 5-week intensive schedule. */
        schedule: z
          .object({
            week: z.number(),
            day: z.number(),
          })
          .optional(),
        /** Static nbconvert render, generated by scripts/build-previews.mjs. */
        preview: z.string().optional(),
      }),
    }),
    // Short "meet the instructor" intros, shown at the top of the index. Kept
    // separate from teachingResources: these are people, not teaching
    // materials, and they should not land in ck-teaching's resource catalog
    // when the lectures port over.
    instructors: defineCollection({
      type: 'data',
      source: 'instructors/**/*.md',
      schema: z.object({
        name: z.string(),
        sequence: z.number(),
        video: z.object({
          provider: z.enum(['vimeo', 'youtube']).default('vimeo'),
          id: z.string(),
          hash: z.string().optional(),
          duration: z.string().optional(),
        }),
      }),
    }),
    pages: defineCollection({
      type: 'page',
      source: '*.md',
      schema: z.object({
        seo: z.object({}).editor({ hidden: true }),
        navigation: z.boolean().editor({ hidden: true }),
      }),
    }),
  },
})
